- name: Install TripleO
  import_tasks: tasks/install_pkgs.yaml

- name: Create stack group
  group:
    name: stack
    state: present

- name: Create stack user
  user:
    name: stack
    group: stack
    state: present
    shell: /bin/bash

- name: Grant sudo privileges to stack user
  copy:
    content: |
      stack ALL=(ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/stack
    owner: root
    group: root
    mode: 0440

- name: Setup hostname
  hostname:
    name: "{{ undercloud_fqdn }}"
  tags: setup

- name: Config /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ undercloud_ip }} {{ undercloud_fqdn }} {{ undercloud_hostname }}"
    insertafter: EOF
    state: present
  tags: setup

