---
- name: Install bmc
  yum:
    name:
      - python-virtualbmc
  tags: install_bmc

- name: Configure vbmc
  shell: vbmc add {{ item.add }} --port {{ item.port }} --username admin --password password --libvirt-uri qemu+ssh://root@192.168.122.1/system
  with_items:
    - { add: 'controller', port: '6003' }
    - { add: 'compute1', port: '6001' }
    - { add: 'compute2', port: '6002' }
  tags: configure_bmc
  ignore_errors: true

- name: start vbmc
  shell: vbmc start {{ item }}
  with_items:
    - compute1
    - controller
  tags: start_bmc

